# coding=utf-8
from django.conf.urls import url, include
from MaterielMonitor import views
from MaterielMonitor import recommed_views
from MaterielMonitor import onboarding_views
from MaterielMonitor import relation_push_views
from MaterielMonitor import mobile_click_views
from MaterielMonitor import strategy_recommend_views
from MaterielMonitor import relation_category_views
from MaterielMonitor import speed_material_views
from MaterielMonitor import hot_material_views
from MaterielMonitor import total_push_views
from MaterielMonitor import team_monitor_views
from MaterielMonitor import speed_material_calc_views

urlpatterns = [

    url(r'^$', views.login_view, name='login'),
    url(r'^login', views.login_view, name='login'),
    url(r'^logout', views.logout_view, name='logout'),
    url(r'^index$', views.index, name='index'),

    url(r'^show_materiel_category/', views.show_materiel_category, name='show_materiel_category'),
    url(r'^show_contribute_category/', views.show_contribute_category, name='show_contribute_category'),
    url(r'^show_recall_category/', views.show_recall_category, name='show_recall_category'),
    url(r'^show_rank/', views.show_rank, name='show_rank'),
    url(r'^show_category_rank/', views.show_category_rank, name='show_category_rank'),
    url(r'^show_relation_rank/', views.show_relation_rank, name='show_relation_rank'),
    url(r'^show_ability_mbloger_rank/', views.show_ability_mbloger_rank, name='show_ability_mbloger_rank'),
    url(r'^show_tag_all/', views.show_tag_all, name='show_tag_all'),
    url(r'^show_collaborative_user/', views.show_collaborative_user, name='show_collaborative_user'),
    url(r'^show_collaborative_monitor/', views.show_collaborative_monitor, name='show_collaborative_monitor'),
    url(r'^show_push_accept_user/', views.show_push_accept_user, name='show_push_accept_user'),
    url(r'^show_update_time/', views.show_update_time, name='show_update_time'),
    url(r'^show_material_feature/', views.show_material_feature, name='show_material_feature'),
    url(r'^show_user_feature/', views.show_user_feature, name='show_user_feature'),
    # url(r'^show_user_feature_click_rate/', recommed_views.show_user_feature_click_rate,
    #     name='show_user_feature_click_rate'),
    url(r'^show_interest_timely_push_real_data/', recommed_views.show_interest_timely_push_real_data,
        name='show_interest_timely_push_real_data'),
    url(r'^show_interest_timely_push_item_data/', recommed_views.show_interest_timely_push_item_data,
        name='show_interest_timely_push_item_data'),
    url(r'^show_interest_push_category/', recommed_views.show_interest_push_category,
        name='show_interest_push_category'),

    url(r'^show_tag_recommend_score/', recommed_views.show_tag_recommend_score, name='show_tag_recommend_score'),
    url(r'^show_tag_recommend_score_v2/', recommed_views.show_tag_recommend_score_v2,
        name='show_tag_recommend_score_v2'),
    url(r'^show_tag_recommend_score_v3/', recommed_views.show_tag_recommend_score_v3,
        name='show_tag_recommend_score_v3'),
    url(r'^show_tag_recommend_score_v4/', recommed_views.show_tag_recommend_score_v4,
        name='show_tag_recommend_score_v4'),
    url(r'^show_tag_recommend_weight/', recommed_views.show_tag_recommend_weight, name='show_tag_recommend_weight'),
    url(r'^show_gold_user/', recommed_views.show_gold_user, name='show_gold_user'),
    url(r'^show_gold_v_user_tag_audit/', recommed_views.show_gold_v_user_tag_audit, name='show_gold_v_user_tag_audit'),
    url(r'^show_mbloger_be_interested/', recommed_views.show_mbloger_be_interested, name='show_mbloger_be_interested'),
    url(r'^show_gold_v_user_tag_static/', recommed_views.show_gold_v_user_tag_static,
        name='show_gold_v_user_tag_static'),
    url(r'^show_push_strategy_static/', recommed_views.show_push_strategy_static, name='show_push_strategy_static'),
    url(r'^show_push_click_tag_static/', recommed_views.show_push_click_tag_static, name='show_push_click_tag_static'),
    url(r'^show_interest_push_date/', recommed_views.show_interest_push_date, name='show_interest_push_date'),
    url(r'^show_similarity_users/', recommed_views.show_similarity_users, name='show_similarity_users'),
    url(r'^show_timely_each_data_push_date/', recommed_views.show_timely_each_data_push_date,
        name='show_timely_each_data_push_date'),

    url(r'^get_recommend_tags/', recommed_views.get_recommend_tags, name='get_recommend_tags'),
    url(r'^category_materiel_detail/', views.show_category_materiel_detail, name='show_category_materiel_detail'),
    url(r'^read_blog/', views.read_blog, name='read_blog'),

    url(r'^materiel_static/', views.materiel_static_view, name='materiel_static'),
    url(r'^contribute_static/', views.contribute_static_view, name='contribute_static'),
    url(r'^recall_static/', views.recall_static_view, name='recall_static'),
    url(r'^rank_static/', views.rank_static_view, name='rank_static'),
    url(r'^rank_active_static/', views.rank_active_static_view, name='rank_static'),
    url(r'^rank_category_static/', views.rank_category_static_view, name='rank_category_static'),
    url(r'^rank_relation_static/', views.rank_relation_static_view, name='rank_relation_static'),
    url(r'^rank_ability_static/', views.rank_ability_static_view, name='rank_ability_static'),

    url(r'^tag_recommend_score/', recommed_views.tag_recommend_score_view, name='tag_recommend_score'),
    url(r'^tag_recommend_score_v2/', recommed_views.tag_recommend_score_view_v2, name='tag_recommend_score_v2'),
    url(r'^tag_recommend_score_v3/', recommed_views.tag_recommend_score_view_v3, name='tag_recommend_score_v3'),
    url(r'^tag_recommend_score_v4/', recommed_views.tag_recommend_score_view_v4, name='tag_recommend_score_v4'),
    url(r'^tag_recommend_weight/', recommed_views.tag_recommend_weight_view, name='tag_recommend_weight'),
    url(r'^gold_v_user_audit/', recommed_views.gold_v_user_audit_view, name='gold_v_user_audit'),
    url(r'^gold_v_user_tag_audit/', recommed_views.gold_v_user_tag_audit_view, name='gold_v_user_tag_audit_view'),
    url(r'^mbloger_be_interested/', recommed_views.mbloger_be_interested_view, name='mbloger_be_interested_view'),
    url(r'^add_f_user_audit/$', recommed_views.add_f_user_audit_view, name='add_f_user_audit'),
    url(r'^accept_user/', recommed_views.accept_user, name='check_user'),
    url(r'^reject_user/', recommed_views.reject_user, name='reject_user'),
    url(r'^reject_f01_user/', recommed_views.reject_f01_user, name='reject_f01_user'),
    url(r'^save_gold_v_user_tag/', recommed_views.save_gold_v_user_tag, name='save_gold_v_user_tag'),
    url(r'^delete_gold_v_user_tag/', recommed_views.delete_gold_v_user_tag, name='delete_gold_v_user_tag'),
    url(r'^push_strategy_static/', recommed_views.push_strategy_static_view, name='push_strategy_static'),
    url(r'^push_click_tag_static/', recommed_views.push_click_tag_static_view, name='push_click_tag_static'),
    url(r'^show_personalise_mbloger_be_interested/', recommed_views.show_personalise_mbloger_be_interested,
        name='show_personalise_mbloger_be_interested'),
    url(r'^personalise_mbloger_be_interested/', recommed_views.personalise_mbloger_be_interested_view,
        name='personalise_mbloger_be_interested'),

    url(r'^remove_blog_interest/', views.remove_blog_interest_view, name='remove_blog_interest'),
    url(r'^remove_blog_relation/', views.remove_blog_relation_view, name='remove_blog_relation'),
    url(r'^search_interest_blog/', views.search_interest_blog, name='search_interest_blog'),
    url(r'^add_black_user/$', views.add_black_user_view, name='add_black_user'),
    url(r'^add_black_user/remove_user/$', views.remove_black_user_view, name='remove_black_user'),
    url(r'^add_black_relation/$', views.add_black_relation_view, name='add_black_relation'),
    url(r'^add_black_relation/remove_relation/$', views.remove_black_relation_view, name='remove_black_relation'),
    url(r'^add_black_keyword/$', views.add_black_keyword_view, name='add_black_keyword'),
    url(r'^add_black_keyword/remove_keyword/$', views.remove_black_keyword_view, name='remove_black_keyword'),
    url(r'^result/', views.show_result_view, name='show_result'),
    url(r'^modify_passwd/', views.modify_passwd_view, name='modify_passwd'),
    url(r'^no_perms$', views.no_perms_view, name='no_perms'),
    url(r'^push_blog/', views.push_blog_view, name='push_blog'),
    url(r'^potential_info/', views.potential_info_view, name='potential_info'),
    url(r'^push_accept_total/', views.push_accept_total_view, name='push_accept_total'),
    url(r'^collaborative_user_static/', views.collaborative_user_view, name='collaborative_user_static'),
    url(r'^collaborative_monitor_static/', views.collaborative_monitor_view, name='collaborative_monitor_static'),
    url(r'^material_feature_static/', views.material_feature_static_view, name='material_feature_static'),
    url(r'^user_feature_static/', views.user_feature_static_view, name='user_feature_static'),
    # url(r'^user_feature_click_rate_static/', recommed_views.user_feature_click_rate_view,
    #     name='user_feature_click_rate_static'),
    url(r'^interest_timely_push_real_data/', recommed_views.interest_timely_push_real_data_view,
        name='interest_timely_push_real_data'),
    url(r'^interest_timely_push_item_data/', recommed_views.interest_timely_push_item_data_view,
        name='interest_timely_push_item_data'),
    url(r'^interest_timely_push_each_data/', recommed_views.interest_timely_push_each_data,
        name='interest_timely_push_each_data'),

    url(r'^insert_f_user/', onboarding_views.insert_f_user, name='insert_f_user'),
    url(r'^f_user_audit/', onboarding_views.f_user_audit_view, name='f_user_audit'),

    url(r'^show_f_user_tag_audit/', onboarding_views.show_f_user_tag_audit, name='show_f_user_tag_audit'),
    url(r'^save_f_user_tag/', onboarding_views.save_f_user_tag, name='save_f_user_tag'),
    url(r'^delete_f_user_tag/', onboarding_views.delete_f_user_tag, name='delete_f_user_tag'),
    url(r'^save_f_user_tag_result/', onboarding_views.save_f_user_tag_result, name='save_f_user_tag_result'),
    url(r'^delete_f_user_tag_result/', onboarding_views.delete_f_user_tag_result, name='delete_f_user_tag_result'),

    url(r'^f_user_audit_result/', onboarding_views.f_user_audit_result_view, name='f_user_audit_result'),
    url(r'^show_f_user_tag_audit_result/', onboarding_views.show_f_user_tag_audit_result,
        name='show_f_user_tag_audit_result'),

    url(r'^push_click_rank/', onboarding_views.push_click_rank_view, name='push_click_rank'),
    url(r'^show_push_click_rank/', onboarding_views.show_push_click_rank, name='show_push_click_rank'),

    url(r'^mbloger_collaborative_recommend/', onboarding_views.mbloger_collaborative_recommend_view,
        name='mbloger_collaborative_recommend'),
    url(r'^mbloger_tag_recommend/', onboarding_views.mbloger_tag_recommend_view,
        name='mbloger_collaborative_recommend'),

    url(r'^get_recommend_white_list/', onboarding_views.get_recommend_white_list, name='get_recommend_white_list'),
    url(r'^show_mbloger_tag_recommend/', onboarding_views.show_mbloger_tag_recommend,
        name='show_mbloger_tag_recommend'),
    url(r'^show_mbloger_collaborative_recommend/', onboarding_views.show_mbloger_collaborative_recommend,
        name='show_mbloger_collaborative_recommend'),

    url(r'^obj_match_recommend/', onboarding_views.obj_match_recommend_view, name='obj_match_recommend'),
    url(r'^show_obj_match_recommend/', onboarding_views.show_obj_match_recommend,
        name='show_obj_match_recommend'),
    url(r'^tag_match_recommend/', onboarding_views.tag_match_recommend_view, name='tag_match_recommend'),
    url(r'^show_tag_match_recommend/', onboarding_views.show_tag_match_recommend,
        name='show_obj_match_recommend'),

    url(r'^inte2ability_match_recommend/', onboarding_views.inte2ability_match_recommend_view,
        name='inte2ability_match_recommend'),
    url(r'^show_inte2ability_match_recommend/', onboarding_views.show_inte2ability_match_recommend,
        name='show_inte2ability_match_recommend'),

    url(r'^similar_mbloger_embedding_info/', views.similar_mbloger_embedding_info_view,
        name='similar_mbloger_embedding_info'),
    url(r'^similar_mbloger_embedding_recommend/', onboarding_views.similar_mbloger_embedding_recommend_view,
        name='similar_mbloger_embedding_recommend', ),
    url(r'^show_similar_mbloger_embedding_recommend/', onboarding_views.show_similar_mbloger_embedding_recommend,
        name='show_similar_mbloger_embedding_recommend'),

    url(r'^show_mbloger_stratgy_push_recomment/', onboarding_views.show_mbloger_stratgy_push_recomment,
        name='show_mbloger_stratgy_push_recomment'),
    url(r'^mbloger_stratgy_push_recomment/', onboarding_views.mbloger_stratgy_push_recomment_view,
        name='mbloger_stratgy_push_recomment', ),
    url(r'^stars_recommend/', onboarding_views.stars_recommend_view, name='stars_recommend', ),
    url(r'^show_stars_recommend/', onboarding_views.show_stars_recommend, name='show_stars_recommend'),
    url(r'^common_friends/', onboarding_views.common_friends_view, name='common_friends'),
    url(r'^show_common_friends/', onboarding_views.show_common_friends, name='show_common_friends'),
    url(r'^cold_boot_recommend/', onboarding_views.cold_boot_recommend_view, name='cold_boot_recommend'),
    url(r'^show_cold_boot_recommend/', onboarding_views.show_cold_boot_recommend, name='show_cold_boot_recommend'),

    url(r'^relation_push_static/', relation_push_views.relation_push_static_view, name='relation_push_static'),
    url(r'^show_relation_push_static/', relation_push_views.show_relation_push_static,
        name='show_relation_push_static'),

    url(r'^mobile_click_static/', mobile_click_views.mobile_click_static_view, name='mobile_click_static'),
    url(r'^show_mobile_click_system/', mobile_click_views.show_mobile_click_system, name='show_mobile_click_system'),
    url(r'^show_mobile_click_factory/', mobile_click_views.show_mobile_click_factory, name='show_mobile_click_factory'),
    url(r'^show_mobile_click_version/', mobile_click_views.show_mobile_click_version, name='show_mobile_click_version'),
    url(r'^show_mobile_click_push_date/', mobile_click_views.show_mobile_click_push_date,
        name='show_mobile_click_push_date'),

    url(r'^mobile_user_portrait_static/', mobile_click_views.mobile_user_portrait_static_view,
        name='mobile_user_portrait_static'),
    url(r'^show_mobile_user_portrait_system/', mobile_click_views.show_mobile_user_portrait_system,
        name='show_mobile_user_portrait_system'),
    url(r'^show_mobile_user_portrait_factory/', mobile_click_views.show_mobile_user_portrait_factory,
        name='show_mobile_user_portrait_factory'),
    url(r'^show_mobile_user_portrait_version/', mobile_click_views.show_mobile_user_portrait_version,
        name='show_mobile_user_portrait_version'),
    url(r'^show_mobile_user_portrait_colum_name/', mobile_click_views.show_mobile_user_portrait_colum_name,
        name='show_mobile_user_portrait_colum_name'),
    url(r'^show_mobile_user_portrait_push_date/', mobile_click_views.show_mobile_user_portrait_push_date,
        name='show_mobile_user_portrait_push_date'),

    url(r'^show_strategy_recommend/', strategy_recommend_views.show_strategy_recommend, name='show_strategy_recommend'),
    url(r'^show_follow_radio_strategy_recommend/', strategy_recommend_views.show_follow_radio_strategy_recommend,
        name='show_follow_radio_strategy_recommend'),
    url(r'^strategy_recommend/', strategy_recommend_views.strategy_recommend, name='strategy_recommend'),
    url(r'^show_all_follow_radio_strategy_recommend/',
        strategy_recommend_views.show_all_follow_radio_strategy_recommend,
        name='show_all_follow_radio_strategy_recommend'),

    url(r'^relation_interest_category_static/', relation_category_views.relation_interest_category_view,
        name='relation_interest_category_static'),
    url(r'^show_relation_interest_category/', relation_category_views.show_relation_interest_category,
        name='show_relation_interest_category'),

    url(r'^speed_materiel_static/', speed_material_views.speed_materiel_static_view, name='speed_materiel_static'),
    url(r'^show_speed_materiel_category/', speed_material_views.show_speed_materiel_category,
        name='show_speed_materiel_category'),
    url(r'^show_speed_materiel_recall/', speed_material_views.show_speed_materiel_recall,
        name='show_speed_materiel_recall'),
    url(r'^show_speed_materiel_feature/', speed_material_views.show_speed_materiel_feature,
        name='show_speed_materiel_feature'),
    url(r'^speed_material_category/', speed_material_views.speed_material_category,
        name='speed_material_category'),

    url(r'^speed_materiel_change/', speed_material_views.speed_materiel_change_view, name='speed_materiel_change'),
    url(r'^show_speed_materiel_category_change/', speed_material_views.show_speed_materiel_category_change,
        name='show_speed_materiel_category_change'),
    url(r'^show_speed_materiel_recall_change/', speed_material_views.show_speed_materiel_recall_change,
        name='show_speed_materiel_recall_change'),
    url(r'^show_speed_materiel_feature_change/', speed_material_views.show_speed_materiel_feature_change,
        name='show_speed_materiel_feature_change'),
    url(r'^speed_recommend_local/', speed_material_views.speed_recommend_local_view,
        name='speed_recommend_local'),
    url(r'^show_speed_recommend_local/', speed_material_views.show_speed_recommend_local,
        name='show_speed_recommend_local'),
    url(r'^save_add_speed_recommend_uid/', speed_material_views.save_add_speed_recommend_uid,
        name='save_add_speed_recommend_uid'),

    url(r'^day_mobile_click_static/', mobile_click_views.day_mobile_click_static_view, name='day_mobile_click_static'),
    url(r'^show_day_mobile_click_system/', mobile_click_views.show_day_mobile_click_system,
        name='show_day_mobile_click_system'),
    url(r'^show_day_mobile_click_factory/', mobile_click_views.show_day_mobile_click_factory,
        name='show_day_mobile_click_factory'),
    url(r'^show_day_mobile_click_version/', mobile_click_views.show_day_mobile_click_version,
        name='show_day_mobile_click_version'),
    url(r'^show_day_mobile_click_calc_date/', mobile_click_views.show_day_mobile_click_calc_date,
        name='show_mobile_click_calc_date'),

    url(r'^mobile_weibo_version_static/', mobile_click_views.mobile_weibo_version_view,
        name='mobile_weibo_version_static'),
    url(r'^show_weibo_version/', mobile_click_views.show_weibo_version, name='show_weibo_version'),
    url(r'^show_mobile_weibo_version_date/', mobile_click_views.show_mobile_weibo_version_date,
        name='show_mobile_weibo_version_date'),

    url(r'^hot_material_static/', hot_material_views.hot_material_static_view, name='hot_material_static'),
    url(r'^show_hot_material_static/', hot_material_views.show_hot_material_static, name='show_hot_material_static'),
    url(r'^delete_hot_material_mid/', hot_material_views.delete_hot_material_mid, name='delete_hot_material_mid'),
    url(r'^show_man_check_material/', hot_material_views.show_man_check_material, name='show_man_check_material'),
    url(r'^show_hot_feed_category_material/', hot_material_views.show_hot_feed_category_material,
        name='show_hot_feed_category_material'),

    url(r'^add_black_interest_keyword/', hot_material_views.interest_add_black_view, name='add_black_interest_keyword'),
    url(r'^interest_add_black/remove_interest_keyword/$', hot_material_views.remove_interest_black_keyword_view,
        name='remove_interest_black_keyword'),
    url(r'^add_black_interest_uid/', hot_material_views.add_black_interest_uid,
        name='add_black_interest_uid'),
    url(r'^interest_add_black/remove_interest_user/$', hot_material_views.remove_black_interest_uid_view,
        name='remove_black_interest_uid'),
    url(r'^interest_add_black/', hot_material_views.interest_add_black,
        name='interest_add_black'),

    url(r'^total_push_click_static/', total_push_views.total_push_click_static_view, name='total_push_click_static'),
    url(r'^show_total_push_click_static/', total_push_views.show_total_push_click_static,
        name='show_total_push_click_static'),

    # 业务监控
    url(r'^team_push_monitor/', team_monitor_views.team_push_monitor_view,
        name='team_push_monitor'),
    url(r'^api/insert_team_push_info_online/', team_monitor_views.insert_team_push_info_online,
        name='insert_team_push_info_online'),
    url(r'^show_team_push_monitor/', team_monitor_views.show_team_push_monitor,
        name='show_team_push_monitor'),
    url(r'^show_team_push_info/', team_monitor_views.show_team_push_info,
        name='show_team_push_info'),
    url(r'^api/insert_team_feed_info_online/', team_monitor_views.insert_team_feed_info_online,
        name='insert_team_feed_info_online'),

    url(r'^team_speed_rec_feed_monitor/', team_monitor_views.team_speed_rec_feed_monitor_view,
        name='team_speed_rec_feed_monitor'),
    url(r'^show_team_speed_rec_feed_monitor/', team_monitor_views.show_team_speed_rec_feed_monitor,
        name='show_team_speed_rec_feed_monitor'),
    url(r'^show_team_feed_info/', team_monitor_views.show_team_feed_info,
        name='show_team_feed_info'),

    url(r'^speed_materiel_calc/', speed_material_calc_views.speed_materiel_calc_view, name='speed_materiel_calc'),
    url(r'^show_speed_material_tag_static_date/', speed_material_calc_views.show_speed_material_tag_static_date,
        name='show_speed_material_tag_static_date'),
    url(r'^show_speed_material_tag_static/', speed_material_calc_views.show_speed_material_tag_static,
         name='show_speed_material_tag_static'),
    url(r'^show_speed_material_recall_static_date/', speed_material_calc_views.show_speed_material_recall_static_date,
        name='show_speed_material_recall_static_date'),
    url(r'^show_speed_material_recall_static/', speed_material_calc_views.show_speed_material_recall_static,
        name='show_speed_material_recall_static'),
    url(r'^speed_materiel_calc1/', speed_material_calc_views.speed_materiel_calc1_view, name='speed_materiel_calc1'),
    url(r'^show_speed_material_newvsold_static_date/', speed_material_calc_views.show_speed_material_newvsold_static_date,
        name='show_speed_material_newvsold_static_date'),
    url(r'^show_speed_material_newvsold_static/', speed_material_calc_views.show_speed_material_newvsold_static,
        name='show_speed_material_newvsold_static'),
    url(r'^speed_materiel_calc2/', speed_material_calc_views.speed_materiel_calc2_view, name='speed_materiel_calc2'),
    url(r'^show_speed_material_uservsvisitor_static_date/', speed_material_calc_views.show_speed_material_uservsvisitor_static_date,
        name='show_speed_material_uservsvisitor_static_date'),
    url(r'^show_speed_material_uservsvisitor_static/', speed_material_calc_views.show_speed_material_uservsvisitor_static,
        name='show_speed_material_uservsvisitor_static'),

]
